[versions]
kotlin = "1.7.10"  # Note: Plugin versions must be updated in the settings.gradle.kts too

groovy = "4.0.2"
kord-extensions = "1.5.5-SNAPSHOT"
logging = "2.1.21"
logback = "1.2.11"
kmongo = "4.6.1"

[libraries]
groovy = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.microutils:kotlin-logging", version.ref = "logging" }

kmongo = { module = "org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo"}
